export interface FormField {
  key: string;
  label: string;
  type: 'text' | 'email' | 'date' | 'textarea';
  placeholder?: string;
}

export const templateFields: Record<string, FormField[]> = {
  'FT-CRD-137-01 Student Application Letter Template': [
    { key: 'date', label: 'Date', type: 'date' },
    { key: 'contactPerson', label: 'Industry Representative Name', type: 'text', placeholder: 'e.g. Mr. Juan dela Cruz' },
    { key: 'contactTitle', label: 'Position / Title', type: 'text', placeholder: 'e.g. HR Manager' },
    { key: 'companyName', label: 'Company Name', type: 'text', placeholder: 'e.g. Acme Corporation' },
    { key: 'companyAddress', label: 'Company Address', type: 'text', placeholder: 'Full address' },
    { key: 'campusName', label: 'Campus Name', type: 'text', placeholder: 'e.g. Global City' },
    { key: 'programName', label: 'Degree / Program Name', type: 'text', placeholder: 'e.g. Bachelor of Science in Information Technology' },
    { key: 'hoursRequired', label: 'Required OJT Hours', type: 'text', placeholder: 'e.g. 486' },
    { key: 'phoneNumber', label: 'Student Phone Number', type: 'text', placeholder: 'e.g. 09XX-XXX-XXXX' },
    { key: 'email', label: 'Student Email Address', type: 'email', placeholder: 'e.g. student@email.com' },
    { key: 'studentName', label: 'Name of Student Trainee', type: 'text', placeholder: 'e.g. Juan Dela Cruz' },
  ],
  'FT-CRD-134-01 Proposal Letter to the Industry Template': [
    { key: 'date', label: 'Date', type: 'date' },
    { key: 'contactPerson', label: 'Industry Representative Name', type: 'text', placeholder: 'e.g. Mr. Juan dela Cruz' },
    { key: 'contactTitle', label: 'Position / Title', type: 'text', placeholder: 'e.g. HR Manager' },
    { key: 'companyName', label: 'Company Name', type: 'text', placeholder: 'e.g. Acme Corporation' },
    { key: 'companyAddress', label: 'Company Address', type: 'text', placeholder: 'Full address' },
    { key: 'studentName', label: 'Student Name (Full)', type: 'text', placeholder: 'e.g. Juan Dela Cruz' },
    { key: 'programName', label: 'Degree / Program Name', type: 'text', placeholder: 'e.g. BSIT' },
    { key: 'hoursRequired', label: 'Required OJT Hours', type: 'text', placeholder: 'e.g. 486' },
    { key: 'coordinatorName', label: 'OJT Coordinator Name', type: 'text', placeholder: 'e.g. Prof. Maria Santos' },
  ],
  'FT-CRD-135-01 STI OJT Endorsement Letter Template': [
    { key: 'date', label: 'Date', type: 'date' },
    { key: 'contactPerson', label: 'Industry Representative Name', type: 'text', placeholder: 'e.g. Mr. Juan dela Cruz' },
    { key: 'contactTitle', label: 'Position / Title', type: 'text', placeholder: 'e.g. HR Manager' },
    { key: 'companyName', label: 'Company Name', type: 'text', placeholder: 'e.g. Acme Corporation' },
    { key: 'companyAddress', label: 'Company Address', type: 'text', placeholder: 'Full address' },
    { key: 'studentName', label: 'Student Name (Full)', type: 'text', placeholder: 'e.g. Juan Dela Cruz' },
    { key: 'programName', label: 'Degree / Program Name', type: 'text', placeholder: 'e.g. BSIT' },
    { key: 'hoursRequired', label: 'Required OJT Hours', type: 'text', placeholder: 'e.g. 486' },
    { key: 'coordinatorName', label: 'OJT Coordinator Name', type: 'text', placeholder: 'e.g. Prof. Maria Santos' },
    { key: 'contactNumber', label: 'Contact Number', type: 'text', placeholder: 'e.g. (02) 8XXX-XXXX' },
    { key: 'schoolEmail', label: 'School Email', type: 'email', placeholder: 'e.g. info@sti.edu' },
  ],
  'FT-CRD-128-01 Memorandum of Agreement (MOA) Template bet. STI and HTE': [
    { key: 'date', label: 'Date', type: 'date' },
    { key: 'stiAddress', label: 'STI Campus Address', type: 'text', placeholder: 'e.g. Cubao, Quezon City' },
    { key: 'stiRepresentative', label: 'STI Representative Name', type: 'text', placeholder: 'e.g. Dr. Maria Santos' },
    { key: 'stiRepTitle', label: 'STI Representative Position', type: 'text', placeholder: 'e.g. School Director' },
    { key: 'companyName', label: 'Company / HTE Name', type: 'text', placeholder: 'e.g. Acme Corporation' },
    { key: 'companyAddress', label: 'Company Address', type: 'text', placeholder: 'Full address' },
    { key: 'hteRepresentative', label: 'HTE Representative Name', type: 'text', placeholder: 'e.g. Mr. Juan dela Cruz' },
    { key: 'hteRepTitle', label: 'HTE Representative Position', type: 'text', placeholder: 'e.g. HR Manager' },
    { key: 'studentName', label: 'Student Trainee Name', type: 'text', placeholder: 'e.g. Juan Dela Cruz' },
    { key: 'startDate', label: 'Start Date', type: 'date' },
    { key: 'endDate', label: 'End Date', type: 'date' },
    { key: 'day', label: 'Day', type: 'text', placeholder: 'e.g. 1st' },
    { key: 'month', label: 'Month', type: 'text', placeholder: 'e.g. August' },
    { key: 'year', label: 'Year', type: 'text', placeholder: 'e.g. 24' },
  ],
  'FT-CRD-131-00 OJT Parent Consent Form without Training Fee Template': [
    { key: 'studentName', label: 'Student Name (Full)', type: 'text', placeholder: 'e.g. Juan Dela Cruz' },
    { key: 'programName', label: 'Degree / Program Name', type: 'text', placeholder: 'e.g. BSIT' },
    { key: 'companyName', label: 'Company Name', type: 'text', placeholder: 'e.g. Acme Corporation' },
    { key: 'companyAddress', label: 'Company Address', type: 'text', placeholder: 'Full address' },
    { key: 'hoursRequired', label: 'Required OJT Hours', type: 'text', placeholder: 'e.g. 486' },
    { key: 'parentName', label: 'Parent / Guardian Name', type: 'text', placeholder: 'e.g. Maria Dela Cruz' },
    { key: 'date', label: 'Date', type: 'date' },
    { key: 'guardianPrintedName', label: 'Guardian Printed Name', type: 'text', placeholder: 'e.g. Maria Dela Cruz' },
    { key: 'guardianContact', label: 'Guardian Contact', type: 'text', placeholder: 'e.g. 09XX-XXX-XXXX' },
    { key: 'relationship', label: 'Relationship', type: 'text', placeholder: 'e.g. Mother' },
  ],
  'FT-CRD-130-00 OJT Parent Consent Form with Training Fee Template': [
    { key: 'studentName', label: 'Student Name (Full)', type: 'text', placeholder: 'e.g. Juan Dela Cruz' },
    { key: 'programName', label: 'Degree / Program Name', type: 'text', placeholder: 'e.g. BSIT' },
    { key: 'companyName', label: 'Company Name', type: 'text', placeholder: 'e.g. Acme Corporation' },
    { key: 'companyAddress', label: 'Company Address', type: 'text', placeholder: 'Full address' },
    { key: 'hoursRequired', label: 'Required OJT Hours', type: 'text', placeholder: 'e.g. 486' },
    { key: 'trainingFee', label: 'Training Fee Amount', type: 'text', placeholder: 'e.g. PHP 500.00' },
    { key: 'parentName', label: 'Parent / Guardian Name', type: 'text', placeholder: 'e.g. Maria Dela Cruz' },
    { key: 'date', label: 'Date', type: 'date' },
    { key: 'guardianPrintedName', label: 'Guardian Printed Name', type: 'text', placeholder: 'e.g. Maria Dela Cruz' },
    { key: 'guardianContact', label: 'Guardian Contact', type: 'text', placeholder: 'e.g. 09XX-XXX-XXXX' },
    { key: 'relationship', label: 'Relationship', type: 'text', placeholder: 'e.g. Mother' },
  ],
  'FT-CRD-139-01 Student Consent Form without Training Fee Template': [
    { key: 'studentName', label: 'Student Name (Full)', type: 'text', placeholder: 'e.g. Juan Dela Cruz' },
    { key: 'courseSection', label: 'Course/Section', type: 'text', placeholder: 'e.g. BSIT 401' },
    { key: 'companyName', label: 'Company Name', type: 'text', placeholder: 'e.g. Acme Corporation' },
    { key: 'companyAddress', label: 'Company Address', type: 'text', placeholder: 'Full address' },
    { key: 'ojtDuration', label: 'OJT Duration', type: 'text', placeholder: 'e.g. 486 Hours' },
    { key: 'date', label: 'Date', type: 'date' },
  ],
  'FT-CRD-138-01 Student Consent Form with Training Fee Template': [
    { key: 'studentName', label: 'Student Name (Full)', type: 'text', placeholder: 'e.g. Juan Dela Cruz' },
    { key: 'courseSection', label: 'Course/Section', type: 'text', placeholder: 'e.g. BSIT 401' },
    { key: 'companyName', label: 'Company Name', type: 'text', placeholder: 'e.g. Acme Corporation' },
    { key: 'companyAddress', label: 'Company Address', type: 'text', placeholder: 'Full address' },
    { key: 'ojtDuration', label: 'OJT Duration', type: 'text', placeholder: 'e.g. 486 Hours' },
    { key: 'trainingFee', label: 'Training Fee Amount', type: 'text', placeholder: 'e.g. PHP 500.00' },
    { key: 'date', label: 'Date', type: 'date' },
  ],
  'FT-CRD-176-00 OJT Training Plan_BSIT-BSCS-BSIS-ACT-ITP': [
    { key: 'studentName', label: 'Student Name', type: 'text' },
    { key: 'courseSection', label: 'Course & Section', type: 'text' },
    { key: 'companyName', label: 'Company', type: 'text' },
    { key: 'companySupervisor', label: 'Company Supervisor', type: 'text' },
    { key: 'startDate', label: 'Start Date', type: 'date' },
    { key: 'endDate', label: 'End Date', type: 'date' },
    { key: 'trainingObjectives', label: 'Training Objectives', type: 'textarea' },
    { key: 'scopeOfWork', label: 'Scope of Work', type: 'textarea' },
    { key: 'technicalSkills', label: 'Technical Skills', type: 'textarea' },
    { key: 'softSkills', label: 'Soft Skills', type: 'textarea' },
  ],
  'FT-CRD-175-00 OJT Training Plan_BSCpE (1)': [
    { key: 'studentName', label: 'Student Name', type: 'text' },
    { key: 'courseSection', label: 'Course & Section', type: 'text' },
    { key: 'companyName', label: 'Company', type: 'text' },
    { key: 'companySupervisor', label: 'Company Supervisor', type: 'text' },
    { key: 'startDate', label: 'Start Date', type: 'date' },
    { key: 'endDate', label: 'End Date', type: 'date' },
    { key: 'trainingObjectives', label: 'Training Objectives', type: 'textarea' },
    { key: 'scopeOfWork', label: 'Scope of Work', type: 'textarea' },
    { key: 'technicalSkills', label: 'Technical Skills', type: 'textarea' },
    { key: 'softSkills', label: 'Soft Skills', type: 'textarea' },
  ],
  'FT-CRD-167-00 Weekly Journal Template': [
    { key: 'studentName', label: 'Student Name', type: 'text' },
    { key: 'courseSection', label: 'Course & Section', type: 'text' },
    { key: 'companyName', label: 'Company', type: 'text' },
    { key: 'supervisor', label: 'Supervisor', type: 'text' },
    { key: 'weekNo', label: 'Week No', type: 'text' },
    { key: 'startDate', label: 'Start Date', type: 'date' },
    { key: 'endDate', label: 'End Date', type: 'date' },
    { key: 'objectives', label: 'Objectives', type: 'textarea' },
    { key: 'activities', label: 'Activities', type: 'textarea' },
    { key: 'challenges', label: 'Challenges', type: 'textarea' },
    { key: 'learnings', label: 'Learnings', type: 'textarea' },
    { key: 'planForNextWeek', label: 'Plan for Next Week', type: 'textarea' },
  ],
  'FT-CRD-133-02 Performance Appraisal Template': [
    { key: 'studentName', label: 'Student Name', type: 'text' },
    { key: 'companyName', label: 'Company Name', type: 'text' },
    { key: 'department', label: 'Department', type: 'text' },
    { key: 'trainingPeriod', label: 'Training Period', type: 'text' },
    { key: 'finalRating', label: 'Final Average Rating', type: 'text' },
    { key: 'comments', label: 'Comments', type: 'textarea' },
    { key: 'supervisor', label: 'Company Supervisor', type: 'text' },
    { key: 'dateSigned', label: 'Date Signed', type: 'date' },
  ],
  'FT-CRD-127-01 Integration Paper Template': [
    { key: 'companyName', label: 'Host Training Establishment', type: 'text' },
    { key: 'programName', label: 'Name of Program', type: 'text' },
    { key: 'studentName', label: 'Student Trainee', type: 'text' },
    { key: 'coordinatorName', label: 'OJT Coordinator', type: 'text' },
    { key: 'date', label: 'Date Submitted', type: 'date' },
  ],
  'sample-dtr': [
    { key: 'studentName', label: 'Student Name', type: 'text' },
    { key: 'courseSection', label: 'Course & Section', type: 'text' },
    { key: 'companyName', label: 'Company', type: 'text' },
    { key: 'monthYear', label: 'Month/Year', type: 'text' },
    { key: 'totalHours', label: 'Total Hours', type: 'text' },
    { key: 'cumulativeHours', label: 'Cumulative Hours', type: 'text' },
  ],
};

// Helper to get the filename from a full path URL
export const getTemplateFilename = (pdfUrl: string): string => {
  const docUrl = pdfUrl.replace(/\.pdf$/i, '');
  const parts = docUrl.split('/');
  return decodeURIComponent(parts[parts.length - 1]);
};
